In [46]:
import numpy as np

In [48]:
def decomp_cholesky(A):
    n = A.shape[0]

    if A.shape[0] != A.shape[1]:
        raise ValueError("A matriz deve ser quadrada.")
    if not np.allclose(A, A.T):
        raise ValueError("A matriz deve ser simetrica.")

    L = np.zeros_like(A)
    for i in range(n):
        for j in range(i+1):
            s = sum(L[i][k] * L[j][k] for k in range(j))
            if i == j:
                L[i][j] = np.sqrt(A[i][i] - s)
            else:
                L[i][j] = (A[i][j] - s) / L[j][j]
    return L

A = np.array([[9, 6, -3, 3],
              [6, 20, 2, 22],
              [-3, 2, 6, 2],
              [3, 22, 2, 28]], dtype=float)

L = decomp_cholesky(A)

Lt = L.T

A_rec = L @ Lt

print("Matriz A original:")
print(A)

print("\nMatriz L obtida na decomposição de Cholesky:")
print(L)

print("\nTransposta de L:")
print(Lt)

print("\nMatriz A reconstruída:")
print(A_rec)


Matriz A original:
[[ 9.  6. -3.  3.]
 [ 6. 20.  2. 22.]
 [-3.  2.  6.  2.]
 [ 3. 22.  2. 28.]]

Matriz L obtida na decomposição de Cholesky:
[[ 3.  0.  0.  0.]
 [ 2.  4.  0.  0.]
 [-1.  1.  2.  0.]
 [ 1.  5. -1.  1.]]

Transposta de L:
[[ 3.  2. -1.  1.]
 [ 0.  4.  1.  5.]
 [ 0.  0.  2. -1.]
 [ 0.  0.  0.  1.]]

Matriz A reconstruída:
[[ 9.  6. -3.  3.]
 [ 6. 20.  2. 22.]
 [-3.  2.  6.  2.]
 [ 3. 22.  2. 28.]]
