### Questão 1

A fórmula de Newton para interpolação polinomial utiliza diferenças divididas. Para um polinômio de grau 3:

$$
P_3(x) = f[x_0] + f[x_0, x_1](x - x_0) + f[x_0, x_1, x_2](x - x_0)(x - x_1) + f[x_0, x_1, x_2, x_3](x - x_0)(x - x_1)(x - x_2)
$$

A integral de uma função $f(x)$ pode ser aproximada por:

$$
\int_a^b f(x)dx \approx \int_a^b P_3(x) dx
$$

Usando as diferenças divididas definidas como:

$$
f[x_i, x_{i+1}] = \frac{f[x_{i+1}] - f[x_i]}{x_{i+1} - x_i}
$$

E assim por diante.


### Questão 2


In [90]:
import numpy as np

def integral_newton_ordem3(func, a, b, n=3):
    if n % 3 != 0:
        raise ValueError("O número de subintervalos deve ser múltiplo de 3.")

    h = (b - a) / n
    x_points = np.linspace(a, b, n + 1)
    y_points = func(x_points)
    
    soma = y_points[0] + y_points[-1]
    soma += 3 * np.sum(y_points[1:-1:3])
    soma += 3 * np.sum(y_points[2:-1:3])
    soma += 2 * np.sum(y_points[3:-1:3])
    
    integral = (3 * h / 8) * soma
    return integral

def f_q2(x):
    return np.sin(100 * x) / x

a_q2, b_q2 = 0.01, 1.0
num_subintervalos = 3000

valor_aproximado = integral_newton_ordem3(f_q2, a_q2, b_q2, n=num_subintervalos)
print(f"Valor Aproximado da Integral (n={num_subintervalos}): {valor_aproximado}")

n_referencia = 300000
valor_referencia = integral_newton_ordem3(f_q2, a_q2, b_q2, n=n_referencia)
print(f"Valor de Referência (n={n_referencia}): {valor_referencia}")

erro_absoluto = abs(valor_referencia - valor_aproximado)
erro_relativo = (erro_absoluto / abs(valor_referencia)) * 100
print(f"Erro Absoluto (vs. referência): {erro_absoluto}")
print(f"Erro Relativo (vs. referência): {erro_relativo:.6f}%\n")

Valor Aproximado da Integral (n=3000): 0.6161423937660417
Valor de Referência (n=300000): 0.6161423965218731
Erro Absoluto (vs. referência): 2.7558313409059565e-09
Erro Relativo (vs. referência): 0.000000%



### Questão 3

In [91]:
import numpy as np

def trapezio(f, a, b, n=100):
    import numpy as np

    h = (b - a) / n
    x = np.linspace(a, b, n+1)
    y = f(x)
    return (h/2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])

def demonstrar_erro():
    def f(x):
        return np.exp(x) * np.sin(10 * x) + 8

    a, b = 0.4, 2.0

    n_precisao = 714
    valor_referencia = trapezio(f, a, b, n_precisao)

    print(f"Valor de Referência (com n = {n_precisao})")
    print(f"Resultado: {valor_referencia:.8f}")

    valor_com_erro = trapezio(f, a, b)

    print(f"\nValor com Erro Visível (com n = 100)")
    print(f"Resultado: {valor_com_erro:.8f}")

    print("\nAnálise do Erro:")
    print(f"Valor de Referência arredondado: {valor_referencia:.3f}")
    print(f"Valor com Erro arredondado:    {valor_com_erro:.3f}")
    
demonstrar_erro()

Valor de Referência (com n = 714)
Resultado: 12.48289317

Valor com Erro Visível (com n = 100)
Resultado: 12.48389304

Análise do Erro:
Valor de Referência arredondado: 12.483
Valor com Erro arredondado:    12.484


### Questão 4

In [92]:
import numpy as np

ano = np.array([1940, 1950, 1960, 1970, 1980, 1991, 2000, 2010, 2022])
pop_urbana = np.array([10.9, 19.4, 32.0, 56.0, 80.1, 110.7, 137.9, 160.9, 172.3])
pop_rural = np.array([30.3, 32.5, 38.0, 37.1, 38.9, 36.1, 31.7, 29.9, 30.8])

x = ano - 1940
x_2025 = 2025 - 1940

def avaliar_polinomio(coef, x):
    resultado = 0
    grau = len(coef) - 1
    for i in range(len(coef)):
        resultado += coef[i] * x**(grau - i)
    return resultado

def melhor_grau(x, y, grau_max):
    melhor_rmse = float('inf')
    melhor_grau = 1
    melhor_coef = None
    for grau in range(1, grau_max + 1):
        coef = np.polyfit(x, y, grau)
        y_pred = np.array([avaliar_polinomio(coef, xi) for xi in x])
        rmse = np.sqrt(np.mean((y - y_pred)**2))
        if rmse < melhor_rmse:
            melhor_rmse = rmse
            melhor_grau = grau
            melhor_coef = coef
    return melhor_grau, melhor_coef

grau_urb, coef_urb = melhor_grau(x, pop_urbana, 5)
pop_urb_2025 = avaliar_polinomio(coef_urb, x_2025)

grau_rur, coef_rur = melhor_grau(x, pop_rural, 5)
pop_rur_2025 = avaliar_polinomio(coef_rur, x_2025)

print(f"Melhor grau População Urbana: {grau_urb}")
print(f"Previsão População Urbana 2025: {pop_urb_2025:.1f} milhões")

print(f"Melhor grau População Rural: {grau_rur}")
print(f"Previsão População Rural 2025: {pop_rur_2025:.1f} milhões")


Melhor grau População Urbana: 5
Previsão População Urbana 2025: 170.1 milhões
Melhor grau População Rural: 5
Previsão População Rural 2025: 32.4 milhões


### Questão 5

In [93]:
import numpy as np

def gauss_pivot_parcial(A_original, b_original):
    A = np.array(A_original, dtype=float)
    b = np.array(b_original, dtype=float)
    n = len(b)

    for k in range(n - 1):
        pivo_linha = k
        max_val = abs(A[k, k])
        for i in range(k + 1, n):
            if abs(A[i, k]) > max_val:
                max_val = abs(A[i, k])
                pivo_linha = i

        if pivo_linha != k:
            A[[k, pivo_linha]] = A[[pivo_linha, k]]
            b[[k, pivo_linha]] = b[[pivo_linha, k]]

        if A[k, k] == 0:
            print(f"Matriz singular detectada na coluna {k}. Não é possível resolver.")
            return None

        for i in range(k + 1, n):
            m = A[i, k] / A[k, k]
            A[i, k:] = A[i, k:] - m * A[k, k:]
            b[i] = b[i] - m * b[k]

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        if A[i, i] == 0:
            print(f"Zero na diagonal principal. Sistema impossível ou indeterminado.")
            return None
        soma_ax = np.dot(A[i, i + 1:], x[i + 1:])
        x[i] = (b[i] - soma_ax) / A[i, i]
        
    return x

A = np.array([
    [1,  0,  0, -2,  0,  0],
    [1,  0,  0,  0, -1,  0],
    [4,  4,  2, -4, -4,  3],
    [0,  2,  0,  0,  0,  0],
    [0,  1,  0, -1, -1,  0],
    [0,  0,  1,  0,  0, -1]
], dtype=float)

b = np.array([0, 0, 1, 2, 0, 0], dtype=float)

solucao_refatorada = gauss_pivot_parcial(A, b)
solucao_numpy = np.linalg.solve(A, b)

print("Solução da função refatorada:")
print(solucao_refatorada)
print("\nSolução do numpy:")
print(solucao_numpy)
print("\nAs soluções são iguais")

Solução da função refatorada:
[ 0.66666667  1.         -0.33333333  0.33333333  0.66666667 -0.33333333]

Solução do numpy:
[ 0.66666667  1.         -0.33333333  0.33333333  0.66666667 -0.33333333]

As soluções são iguais


### Questão 6

In [94]:
import numpy as np

def decomp_lu_pivot(A, b):
    n = A.shape[0]
    L = np.identity(n, dtype=float)
    U = A.astype(float).copy()
    p = np.arange(n)

    for k in range(n - 1):
        pivot_row_index = np.argmax(np.abs(U[k:, k])) + k
        
        if pivot_row_index != k:
            U[[k, pivot_row_index]] = U[[pivot_row_index, k]]
            p[[k, pivot_row_index]] = p[[pivot_row_index, k]]
            if k > 0:
                L[[k, pivot_row_index], :k] = L[[pivot_row_index, k], :k]
        
        for i in range(k + 1, n):
            L[i, k] = U[i, k] / U[k, k]
            U[i, k:] -= L[i, k] * U[k, k:]
            U[i, k] = 0
    
    b_permuted = b[p]

    y = np.zeros(n)
    for i in range(n):
        y[i] = b_permuted[i] - np.dot(L[i, :i], y[:i])

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
        
    return x

A = np.array([
    [1,  0,  0, -2,  0,  0],
    [1, 0,  0,  0, -1,  0],
    [4,  4,  2, -4, -4,  3],
    [0,  2,  0, 0,  0,  0],
    [0,  1,  0, -1, -1,  0],
    [0,  0,  1,  0,  0, -1]
], dtype=float)

b = np.array([0, 0, 1, 2, 0, 0], dtype=float)

solucao_final = decomp_lu_pivot(A, b)

print(solucao_final)

[ 0.66666667  1.         -0.33333333  0.33333333  0.66666667 -0.33333333]
